spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/subway'
    username: 'root'
    password: 'masterpw'
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
